nodeLinker: node-modules

# Suppress warnings for faster builds
logFilters:
  - code: YN0002
    level: discard # Suppress missing peer dependency warnings
  - code: YN0060
    level: discard # Suppress workspace warnings
  - code: YN0006
    level: discard # Suppress cache warnings
  - code: YN0013
    level: discard # Suppress resolution warnings
  - code: YN0018
    level: discard # Suppress package conflicts

# Faster installs with conflict resolution
enableGlobalCache: false
compressionLevel: 0
preferDeferredVersions: true

# Network optimization (reduced timeouts)
httpTimeout: 180000
networkTimeout: 180000

# Performance optimization
enableHardenedMode: false
enableInlineBuilds: true
