nodeLinker: node-modules

# Suppress warnings for faster builds
logFilters:
  - code: YN0002
    level: discard # Suppress missing peer dependency warnings
  - code: YN0060
    level: discard # Suppress workspace warnings
  - code: YN0006
    level: discard # Suppress cache warnings

# Faster installs
enableGlobalCache: false
compressionLevel: 0

# Network optimization
httpTimeout: 600000
networkTimeout: 600000
