/**
 * Migration: Add InventoryTransactions Permissions
 *
 * Creates inventoryTransactions role and permissions with role hierarchy support.
 * The inventoryTransactions role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates inventoryTransactions role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: inventoryTransactions (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under inventoryTransactions later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:inventoryTransactions
 * Domain: inventory/operations
 * Generated: 2025-12-08T02:57:16.822Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * InventoryTransactions permissions definition
 */
const INVENTORYTRANSACTIONS_PERMISSIONS = [
  {
    resource: 'inventory:inventoryTransactions',
    action: 'create',
    description: 'Create inventoryTransactions',
  },
  {
    resource: 'inventory:inventoryTransactions',
    action: 'read',
    description: 'Read inventoryTransactions',
  },
  {
    resource: 'inventory:inventoryTransactions',
    action: 'update',
    description: 'Update inventoryTransactions',
  },
  {
    resource: 'inventory:inventoryTransactions',
    action: 'delete',
    description: 'Delete inventoryTransactions',
  },
  {
    resource: 'inventory:inventoryTransactions',
    action: 'export',
    description: 'Export inventoryTransactions',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating inventoryTransactions role and permissions...',
  );

  // Step 1: Create inventoryTransactions role with admin as parent
  // This ensures inventoryTransactions role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'inventoryTransactions',
    'InventoryTransactions module role',
    'admin',
  );

  // Step 2: Create permissions and assign to inventoryTransactions role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, INVENTORYTRANSACTIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'inventoryTransactions',
        permissions: INVENTORYTRANSACTIONS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] InventoryTransactions role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing inventoryTransactions permissions...');

  await removePermissions(knex, INVENTORYTRANSACTIONS_PERMISSIONS);

  console.log(
    '[Migration] InventoryTransactions permissions removed successfully',
  );
}
