/**
 * Migration: Add DrugReturnItems Permissions
 *
 * Creates drugReturnItems role and permissions with role hierarchy support.
 * The drugReturnItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugReturnItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugReturnItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugReturnItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugReturnItems
 * Domain: inventory/operations
 * Generated: 2025-12-08T02:57:53.254Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugReturnItems permissions definition
 */
const DRUGRETURNITEMS_PERMISSIONS = [
  {
    resource: 'inventory:drugReturnItems',
    action: 'create',
    description: 'Create drugReturnItems',
  },
  {
    resource: 'inventory:drugReturnItems',
    action: 'read',
    description: 'Read drugReturnItems',
  },
  {
    resource: 'inventory:drugReturnItems',
    action: 'update',
    description: 'Update drugReturnItems',
  },
  {
    resource: 'inventory:drugReturnItems',
    action: 'delete',
    description: 'Delete drugReturnItems',
  },
  {
    resource: 'inventory:drugReturnItems',
    action: 'export',
    description: 'Export drugReturnItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugReturnItems role and permissions...');

  // Step 1: Create drugReturnItems role with admin as parent
  // This ensures drugReturnItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugReturnItems',
    'DrugReturnItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugReturnItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGRETURNITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugReturnItems',
        permissions: DRUGRETURNITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugReturnItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugReturnItems permissions...');

  await removePermissions(knex, DRUGRETURNITEMS_PERMISSIONS);

  console.log('[Migration] DrugReturnItems permissions removed successfully');
}
