/**
 * Migration: Add Receipts Permissions
 *
 * Creates receipts role and permissions with role hierarchy support.
 * The receipts role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates receipts role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: receipts (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under receipts later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:receipts
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:56:33.743Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * Receipts permissions definition
 */
const RECEIPTS_PERMISSIONS = [
  {
    resource: 'inventory:receipts',
    action: 'create',
    description: 'Create receipts',
  },
  {
    resource: 'inventory:receipts',
    action: 'read',
    description: 'Read receipts',
  },
  {
    resource: 'inventory:receipts',
    action: 'update',
    description: 'Update receipts',
  },
  {
    resource: 'inventory:receipts',
    action: 'delete',
    description: 'Delete receipts',
  },
  {
    resource: 'inventory:receipts',
    action: 'export',
    description: 'Export receipts',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating receipts role and permissions...');

  // Step 1: Create receipts role with admin as parent
  // This ensures receipts role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'receipts',
    'Receipts module role',
    'admin',
  );

  // Step 2: Create permissions and assign to receipts role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, RECEIPTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'receipts',
        permissions: RECEIPTS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log('[Migration] Receipts role and permissions created successfully');
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing receipts permissions...');

  await removePermissions(knex, RECEIPTS_PERMISSIONS);

  console.log('[Migration] Receipts permissions removed successfully');
}
