/**
 * Migration: Add PurchaseOrderItems Permissions
 *
 * Creates purchaseOrderItems role and permissions with role hierarchy support.
 * The purchaseOrderItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates purchaseOrderItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: purchaseOrderItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under purchaseOrderItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:purchaseOrderItems
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:46:28.679Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * PurchaseOrderItems permissions definition
 */
const PURCHASEORDERITEMS_PERMISSIONS = [
  {
    resource: 'inventory:purchaseOrderItems',
    action: 'create',
    description: 'Create purchaseOrderItems',
  },
  {
    resource: 'inventory:purchaseOrderItems',
    action: 'read',
    description: 'Read purchaseOrderItems',
  },
  {
    resource: 'inventory:purchaseOrderItems',
    action: 'update',
    description: 'Update purchaseOrderItems',
  },
  {
    resource: 'inventory:purchaseOrderItems',
    action: 'delete',
    description: 'Delete purchaseOrderItems',
  },
  {
    resource: 'inventory:purchaseOrderItems',
    action: 'export',
    description: 'Export purchaseOrderItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating purchaseOrderItems role and permissions...',
  );

  // Step 1: Create purchaseOrderItems role with admin as parent
  // This ensures purchaseOrderItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'purchaseOrderItems',
    'PurchaseOrderItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to purchaseOrderItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, PURCHASEORDERITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'purchaseOrderItems',
        permissions: PURCHASEORDERITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] PurchaseOrderItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing purchaseOrderItems permissions...');

  await removePermissions(knex, PURCHASEORDERITEMS_PERMISSIONS);

  console.log(
    '[Migration] PurchaseOrderItems permissions removed successfully',
  );
}
