/**
 * Migration: Add DrugReturns Permissions
 *
 * Creates drugReturns role and permissions with role hierarchy support.
 * The drugReturns role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugReturns role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugReturns (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugReturns later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugReturns
 * Domain: inventory/operations
 * Generated: 2025-12-08T02:57:46.646Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugReturns permissions definition
 */
const DRUGRETURNS_PERMISSIONS = [
  {
    resource: 'inventory:drugReturns',
    action: 'create',
    description: 'Create drugReturns',
  },
  {
    resource: 'inventory:drugReturns',
    action: 'read',
    description: 'Read drugReturns',
  },
  {
    resource: 'inventory:drugReturns',
    action: 'update',
    description: 'Update drugReturns',
  },
  {
    resource: 'inventory:drugReturns',
    action: 'delete',
    description: 'Delete drugReturns',
  },
  {
    resource: 'inventory:drugReturns',
    action: 'export',
    description: 'Export drugReturns',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugReturns role and permissions...');

  // Step 1: Create drugReturns role with admin as parent
  // This ensures drugReturns role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugReturns',
    'DrugReturns module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugReturns role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGRETURNS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugReturns',
        permissions: DRUGRETURNS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugReturns role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugReturns permissions...');

  await removePermissions(knex, DRUGRETURNS_PERMISSIONS);

  console.log('[Migration] DrugReturns permissions removed successfully');
}
