/**
 * Migration: Add ReceiptInspectors Permissions
 *
 * Creates receiptInspectors role and permissions with role hierarchy support.
 * The receiptInspectors role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates receiptInspectors role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: receiptInspectors (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under receiptInspectors later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:receiptInspectors
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:56:47.452Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * ReceiptInspectors permissions definition
 */
const RECEIPTINSPECTORS_PERMISSIONS = [
  {
    resource: 'inventory:receiptInspectors',
    action: 'create',
    description: 'Create receiptInspectors',
  },
  {
    resource: 'inventory:receiptInspectors',
    action: 'read',
    description: 'Read receiptInspectors',
  },
  {
    resource: 'inventory:receiptInspectors',
    action: 'update',
    description: 'Update receiptInspectors',
  },
  {
    resource: 'inventory:receiptInspectors',
    action: 'delete',
    description: 'Delete receiptInspectors',
  },
  {
    resource: 'inventory:receiptInspectors',
    action: 'export',
    description: 'Export receiptInspectors',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating receiptInspectors role and permissions...');

  // Step 1: Create receiptInspectors role with admin as parent
  // This ensures receiptInspectors role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'receiptInspectors',
    'ReceiptInspectors module role',
    'admin',
  );

  // Step 2: Create permissions and assign to receiptInspectors role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, RECEIPTINSPECTORS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'receiptInspectors',
        permissions: RECEIPTINSPECTORS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] ReceiptInspectors role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing receiptInspectors permissions...');

  await removePermissions(knex, RECEIPTINSPECTORS_PERMISSIONS);

  console.log('[Migration] ReceiptInspectors permissions removed successfully');
}
