/**
 * Migration: Add PurchaseRequests Permissions
 *
 * Creates purchaseRequests role and permissions with role hierarchy support.
 * The purchaseRequests role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates purchaseRequests role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: purchaseRequests (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under purchaseRequests later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:purchaseRequests
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:46:35.434Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * PurchaseRequests permissions definition
 */
const PURCHASEREQUESTS_PERMISSIONS = [
  {
    resource: 'inventory:purchaseRequests',
    action: 'create',
    description: 'Create purchaseRequests',
  },
  {
    resource: 'inventory:purchaseRequests',
    action: 'read',
    description: 'Read purchaseRequests',
  },
  {
    resource: 'inventory:purchaseRequests',
    action: 'update',
    description: 'Update purchaseRequests',
  },
  {
    resource: 'inventory:purchaseRequests',
    action: 'delete',
    description: 'Delete purchaseRequests',
  },
  {
    resource: 'inventory:purchaseRequests',
    action: 'export',
    description: 'Export purchaseRequests',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating purchaseRequests role and permissions...');

  // Step 1: Create purchaseRequests role with admin as parent
  // This ensures purchaseRequests role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'purchaseRequests',
    'PurchaseRequests module role',
    'admin',
  );

  // Step 2: Create permissions and assign to purchaseRequests role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, PURCHASEREQUESTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'purchaseRequests',
        permissions: PURCHASEREQUESTS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] PurchaseRequests role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing purchaseRequests permissions...');

  await removePermissions(knex, PURCHASEREQUESTS_PERMISSIONS);

  console.log('[Migration] PurchaseRequests permissions removed successfully');
}
