/**
 * Migration: Add ReceiptItems Permissions
 *
 * Creates receiptItems role and permissions with role hierarchy support.
 * The receiptItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates receiptItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: receiptItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under receiptItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:receiptItems
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:56:40.720Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * ReceiptItems permissions definition
 */
const RECEIPTITEMS_PERMISSIONS = [
  {
    resource: 'inventory:receiptItems',
    action: 'create',
    description: 'Create receiptItems',
  },
  {
    resource: 'inventory:receiptItems',
    action: 'read',
    description: 'Read receiptItems',
  },
  {
    resource: 'inventory:receiptItems',
    action: 'update',
    description: 'Update receiptItems',
  },
  {
    resource: 'inventory:receiptItems',
    action: 'delete',
    description: 'Delete receiptItems',
  },
  {
    resource: 'inventory:receiptItems',
    action: 'export',
    description: 'Export receiptItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating receiptItems role and permissions...');

  // Step 1: Create receiptItems role with admin as parent
  // This ensures receiptItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'receiptItems',
    'ReceiptItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to receiptItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, RECEIPTITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'receiptItems',
        permissions: RECEIPTITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] ReceiptItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing receiptItems permissions...');

  await removePermissions(knex, RECEIPTITEMS_PERMISSIONS);

  console.log('[Migration] ReceiptItems permissions removed successfully');
}
