/**
 * Migration: Add PurchaseOrders Permissions
 *
 * Creates purchaseOrders role and permissions with role hierarchy support.
 * The purchaseOrders role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates purchaseOrders role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: purchaseOrders (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under purchaseOrders later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:purchaseOrders
 * Domain: inventory/procurement
 * Generated: 2025-12-08T02:46:20.911Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * PurchaseOrders permissions definition
 */
const PURCHASEORDERS_PERMISSIONS = [
  {
    resource: 'inventory:purchaseOrders',
    action: 'create',
    description: 'Create purchaseOrders',
  },
  {
    resource: 'inventory:purchaseOrders',
    action: 'read',
    description: 'Read purchaseOrders',
  },
  {
    resource: 'inventory:purchaseOrders',
    action: 'update',
    description: 'Update purchaseOrders',
  },
  {
    resource: 'inventory:purchaseOrders',
    action: 'delete',
    description: 'Delete purchaseOrders',
  },
  {
    resource: 'inventory:purchaseOrders',
    action: 'export',
    description: 'Export purchaseOrders',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating purchaseOrders role and permissions...');

  // Step 1: Create purchaseOrders role with admin as parent
  // This ensures purchaseOrders role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'purchaseOrders',
    'PurchaseOrders module role',
    'admin',
  );

  // Step 2: Create permissions and assign to purchaseOrders role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, PURCHASEORDERS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'purchaseOrders',
        permissions: PURCHASEORDERS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] PurchaseOrders role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing purchaseOrders permissions...');

  await removePermissions(knex, PURCHASEORDERS_PERMISSIONS);

  console.log('[Migration] PurchaseOrders permissions removed successfully');
}
