/**
 * Migration: Add BudgetRequestComments Permissions
 *
 * Creates budgetRequestComments role and permissions with role hierarchy support.
 * The budgetRequestComments role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates budgetRequestComments role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: budgetRequestComments (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under budgetRequestComments later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:budgetRequestComments
 * Domain: inventory/budget
 * Generated: 2025-12-08T15:20:29.848Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * BudgetRequestComments permissions definition
 */
const BUDGETREQUESTCOMMENTS_PERMISSIONS = [
  {
    resource: 'inventory:budgetRequestComments',
    action: 'create',
    description: 'Create budgetRequestComments',
  },
  {
    resource: 'inventory:budgetRequestComments',
    action: 'read',
    description: 'Read budgetRequestComments',
  },
  {
    resource: 'inventory:budgetRequestComments',
    action: 'update',
    description: 'Update budgetRequestComments',
  },
  {
    resource: 'inventory:budgetRequestComments',
    action: 'delete',
    description: 'Delete budgetRequestComments',
  },
  {
    resource: 'inventory:budgetRequestComments',
    action: 'export',
    description: 'Export budgetRequestComments',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating budgetRequestComments role and permissions...',
  );

  // Step 1: Create budgetRequestComments role with admin as parent
  // This ensures budgetRequestComments role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'budgetRequestComments',
    'BudgetRequestComments module role',
    'admin',
  );

  // Step 2: Create permissions and assign to budgetRequestComments role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, BUDGETREQUESTCOMMENTS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'budgetRequestComments',
        permissions: BUDGETREQUESTCOMMENTS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] BudgetRequestComments role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing budgetRequestComments permissions...');

  await removePermissions(knex, BUDGETREQUESTCOMMENTS_PERMISSIONS);

  console.log(
    '[Migration] BudgetRequestComments permissions removed successfully',
  );
}
