/**
 * Migration: Add DrugDistributionItems Permissions
 *
 * Creates drugDistributionItems role and permissions with role hierarchy support.
 * The drugDistributionItems role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugDistributionItems role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugDistributionItems (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugDistributionItems later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugDistributionItems
 * Domain: inventory/operations
 * Generated: 2025-12-08T02:57:39.565Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugDistributionItems permissions definition
 */
const DRUGDISTRIBUTIONITEMS_PERMISSIONS = [
  {
    resource: 'inventory:drugDistributionItems',
    action: 'create',
    description: 'Create drugDistributionItems',
  },
  {
    resource: 'inventory:drugDistributionItems',
    action: 'read',
    description: 'Read drugDistributionItems',
  },
  {
    resource: 'inventory:drugDistributionItems',
    action: 'update',
    description: 'Update drugDistributionItems',
  },
  {
    resource: 'inventory:drugDistributionItems',
    action: 'delete',
    description: 'Delete drugDistributionItems',
  },
  {
    resource: 'inventory:drugDistributionItems',
    action: 'export',
    description: 'Export drugDistributionItems',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log(
    '[Migration] Creating drugDistributionItems role and permissions...',
  );

  // Step 1: Create drugDistributionItems role with admin as parent
  // This ensures drugDistributionItems role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugDistributionItems',
    'DrugDistributionItems module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugDistributionItems role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGDISTRIBUTIONITEMS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugDistributionItems',
        permissions: DRUGDISTRIBUTIONITEMS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugDistributionItems role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugDistributionItems permissions...');

  await removePermissions(knex, DRUGDISTRIBUTIONITEMS_PERMISSIONS);

  console.log(
    '[Migration] DrugDistributionItems permissions removed successfully',
  );
}
