/**
 * Migration: Add DrugDistributions Permissions
 *
 * Creates drugDistributions role and permissions with role hierarchy support.
 * The drugDistributions role inherits from admin role automatically.
 *
 * Features:
 * - Idempotent: Safe to run multiple times
 * - Atomic: All operations in transaction
 * - Hierarchical: Supports role inheritance via parent_id
 * - Module role: Creates drugDistributions role and links all permissions to it
 * - Admin access: Admin role has wildcard permission (*:*) for automatic full access
 *
 * Architecture:
 * - Level 1: admin (parent_id: NULL) → Has *:* wildcard permission
 * - Level 2: drugDistributions (parent_id: admin.id) ← Creates this
 * - Level 3: Custom roles can be created under drugDistributions later
 *
 * Generated by: CRUD Generator v2.1.0
 * Resource: inventory:drugDistributions
 * Domain: inventory/operations
 * Generated: 2025-12-08T02:57:31.684Z
 */

import { Knex } from 'knex';
import {
  createPermissions,
  createRoleIfNotExists,
  removePermissions,
} from '../migrations/helpers/permission-helper.js';

/**
 * DrugDistributions permissions definition
 */
const DRUGDISTRIBUTIONS_PERMISSIONS = [
  {
    resource: 'inventory:drugDistributions',
    action: 'create',
    description: 'Create drugDistributions',
  },
  {
    resource: 'inventory:drugDistributions',
    action: 'read',
    description: 'Read drugDistributions',
  },
  {
    resource: 'inventory:drugDistributions',
    action: 'update',
    description: 'Update drugDistributions',
  },
  {
    resource: 'inventory:drugDistributions',
    action: 'delete',
    description: 'Delete drugDistributions',
  },
  {
    resource: 'inventory:drugDistributions',
    action: 'export',
    description: 'Export drugDistributions',
  },
];

/**
 * Apply migration
 */
export async function up(knex: Knex): Promise<void> {
  console.log('[Migration] Creating drugDistributions role and permissions...');

  // Step 1: Create drugDistributions role with admin as parent
  // This ensures drugDistributions role is part of the hierarchy
  await createRoleIfNotExists(
    knex,
    'drugDistributions',
    'DrugDistributions module role',
    'admin',
  );

  // Step 2: Create permissions and assign to drugDistributions role
  // Admin role has wildcard permission (*:*) and doesn't need explicit assignment
  await createPermissions(knex, DRUGDISTRIBUTIONS_PERMISSIONS, {
    roleAssignments: [
      {
        roleId: 'drugDistributions',
        permissions: DRUGDISTRIBUTIONS_PERMISSIONS,
      },
      // Admin role access via wildcard (*:*) - no explicit assignment needed
    ],
  });

  console.log(
    '[Migration] DrugDistributions role and permissions created successfully',
  );
}

/**
 * Rollback migration
 */
export async function down(knex: Knex): Promise<void> {
  console.log('[Migration] Removing drugDistributions permissions...');

  await removePermissions(knex, DRUGDISTRIBUTIONS_PERMISSIONS);

  console.log('[Migration] DrugDistributions permissions removed successfully');
}
