import type { Knex } from 'knex';

/**
 * Migration: Add Simpletest permissions and roles
 * Generated by CRUD Generator on 2025-10-05T06:40:00.369Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding Simpletest permissions and roles...');

  // Insert permissions for simpletest
  const permissions = [
    {
      description: 'Create simpletest',
      resource: 'simpletest',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read simpletest',
      resource: 'simpletest',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update simpletest',
      resource: 'simpletest',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete simpletest',
      resource: 'simpletest',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for simpletest...`,
  );
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for simpletest
  const roles = [
    {
      name: 'simpletest',
      description: 'Access to simpletest',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for simpletest...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // simpletest role permissions
  const mainRole = await knex('roles').where('name', 'simpletest').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'simpletest')
      .whereIn('action')
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to simpletest role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ Simpletest permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing Simpletest permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['simpletest'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for simpletest...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing simpletest role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['simpletest'])
    .del();

  // Remove permissions
  console.log(`📝 Removing simpletest permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'simpletest')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for simpletest`,
  );
}
