import type { Knex } from 'knex';

/**
 * Migration: Add SimpleTests permissions and roles
 * Generated by CRUD Generator on 2025-10-05T06:14:59.429Z
 */

export async function up(knex: Knex): Promise<void> {
  console.log('🔐 Adding SimpleTests permissions and roles...');

  // Insert permissions for simpleTests
  const permissions = [
    {
      description: 'Create simpleTests',
      resource: 'simpleTests',
      action: 'create',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Read simpleTests',
      resource: 'simpleTests',
      action: 'read',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Update simpleTests',
      resource: 'simpleTests',
      action: 'update',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      description: 'Delete simpleTests',
      resource: 'simpleTests',
      action: 'delete',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(
    `📝 Inserting ${permissions.length} permissions for simpleTests...`,
  );
  await knex('permissions')
    .insert(permissions)
    .onConflict(['resource', 'action'])
    .ignore();

  // Insert roles for simpleTests
  const roles = [
    {
      name: 'simpleTests',
      description: 'Access to simpleTests',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  console.log(`🏷️  Inserting ${roles.length} roles for simpleTests...`);
  await knex('roles').insert(roles).onConflict('name').ignore();

  // Link role permissions
  // simpleTests role permissions
  const mainRole = await knex('roles').where('name', 'simpleTests').first();
  if (mainRole) {
    const mainPermissions = await knex('permissions')
      .where('resource', 'simpleTests')
      .whereIn('action')
      .select('id');

    if (mainPermissions.length > 0) {
      const rolePermissions = mainPermissions.map((p) => ({
        role_id: mainRole.id,
        permission_id: p.id,
        created_at: new Date(),
      }));

      console.log(
        `🔗 Linking ${mainPermissions.length} permissions to simpleTests role...`,
      );
      await knex('role_permissions')
        .insert(rolePermissions)
        .onConflict(['role_id', 'permission_id'])
        .ignore();
    }
  }

  console.log('✅ SimpleTests permissions and roles added successfully');
}

export async function down(knex: Knex): Promise<void> {
  console.log('🗑️  Removing SimpleTests permissions and roles...');

  // Remove role permissions first
  const roleIds = await knex('roles')
    .whereIn('name', ['simpleTests'])
    .pluck('id');

  if (roleIds.length > 0) {
    console.log(`🔗 Removing role permissions for simpleTests...`);
    await knex('role_permissions').whereIn('role_id', roleIds).del();
  }

  // Remove roles
  console.log(`🏷️  Removing simpleTests role...`);
  const deletedRoles = await knex('roles')
    .whereIn('name', ['simpleTests'])
    .del();

  // Remove permissions
  console.log(`📝 Removing simpleTests permissions...`);
  const deletedPermissions = await knex('permissions')
    .where('resource', 'simpleTests')
    .del();

  console.log(
    `✅ Removed ${deletedRoles} roles and ${deletedPermissions} permissions for simpleTests`,
  );
}
