/**
 * ED Groups (Essential Drugs Therapeutic Groups) Seed
 *
 * Seeds the ed_groups table with standard NLEM therapeutic classification.
 * This is standard reference data based on Thai NLEM (National List of Essential Medicines).
 *
 * Uses upsert pattern to safely re-run on upgrades.
 */

import type { Knex } from 'knex';

// ============================================================================
// ED Groups Data (209 records - NLEM Therapeutic Classification)
// ============================================================================

const ED_GROUPS = [
  {
    id: 1,
    code: '01000000',
    name: 'Gastro-intestinal system',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 2,
    code: '01010000',
    name: 'Antacids and other drugs for dyspepsia',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 3,
    code: '01020000',
    name: 'Antispasmodics and other drugs altering gut motility',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 4,
    code: '01030000',
    name: 'Ulcer-healing drugs and drugs used in variceal bleeding',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 5,
    code: '01040000',
    name: 'Drugs used in acute diarrhoea',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 6,
    code: '01050000',
    name: 'Drugs used in chronic bowel disorders',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 7,
    code: '01060000',
    name: 'Laxatives',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 8,
    code: '01070000',
    name: 'Local preparations for anal and rectal disorders',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 9,
    code: '01080000',
    name: 'Drugs affecting intestinal secretions',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 10,
    code: '02000000',
    name: 'Cardiovascular system',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 11,
    code: '02010000',
    name: 'Positive inotropic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 12,
    code: '02020000',
    name: 'Diuretics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 13,
    code: '02030000',
    name: 'Anti-arrhythmic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 14,
    code: '02040000',
    name: 'Beta-adrenoceptor blocking drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 15,
    code: '02050000',
    name: 'Drugs affecting the renin-angiotensin system and some other',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 16,
    code: '02050100',
    name: 'Vasodilator antihypertensive drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 17,
    code: '02050200',
    name: 'Centrally acting antihypertensive drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 18,
    code: '02050300',
    name: 'Alpha-adrenoceptor blocking drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 19,
    code: '02050400',
    name: 'Angiotensin-converting enzyme inhibitors',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 20,
    code: '02050500',
    name: 'Angiotensin-II receptor antagonists',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 21,
    code: '02060000',
    name: 'Nitrates, calcium-channel blockers and other vasodilators',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 22,
    code: '02060100',
    name: 'Nitrates',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 23,
    code: '02060200',
    name: 'Calcium-channel blockers',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 24,
    code: '02060300',
    name: 'Other vasodilators',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 25,
    code: '02070000',
    name: 'Sympathomimetics',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 26,
    code: '02070100',
    name: 'Inotropic sympathomimetics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 27,
    code: '02070200',
    name: 'Vasoconstrictor sympathomimetics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 28,
    code: '02070300',
    name: 'Drugs used in cardiopulmonary resuscitation',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 29,
    code: '02080000',
    name: 'Anticoagulants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 30,
    code: '02090000',
    name: 'Antiplatelet drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 31,
    code: '02100000',
    name: 'Fibrinolytic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 32,
    code: '02110000',
    name: 'Haemostatics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 33,
    code: '02120000',
    name: 'Lipid-regulating drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 34,
    code: '03000000',
    name: 'Respiratory system',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 35,
    code: '03010000',
    name: 'Bronchodilators',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 36,
    code: '03010100',
    name: 'Adrenoceptor agonists',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 37,
    code: '03010200',
    name: 'Compound antimuscarinic bronchodilators',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 38,
    code: '03010300',
    name: 'Theophylline',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 39,
    code: '03020000',
    name: 'Corticosteroids',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 40,
    code: '03030000',
    name: 'Leukotriene receptor antagonists',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 41,
    code: '03040000',
    name: 'Antihistamines',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 42,
    code: '03050000',
    name: 'Pulmonary surfactants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 43,
    code: '03060000',
    name: 'Cough preparations',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 44,
    code: '03060100',
    name: 'Cough suppressants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 45,
    code: '03060200',
    name: 'Expectorant and demulcent cough preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 46,
    code: '03070000',
    name: 'Systemic nasal decongestants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 47,
    code: '03080000',
    name: 'Other respiratory preparations',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 48,
    code: '04000000',
    name: 'Central nervous system',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 49,
    code: '04010000',
    name: 'Hypnotics and anxiolytics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 50,
    code: '04020000',
    name: 'Drugs used in psychoses and related disorders',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 51,
    code: '04020100',
    name: 'Antipsychotic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 52,
    code: '04020200',
    name: 'Antimanic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 53,
    code: '04030000',
    name: 'Antidepressant drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 54,
    code: '04040000',
    name: 'Central nervous system stimulants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 55,
    code: '04050000',
    name: 'Drugs used in nausea and vertigo',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 56,
    code: '04050100',
    name: 'Drugs used in nausea and vomiting',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 57,
    code: '04050200',
    name: 'Drugs used in vestibular disorders',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 58,
    code: '04060000',
    name: 'Analgesics and antipyretics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 59,
    code: '04070000',
    name: 'Analgesics',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 60,
    code: '04070100',
    name: 'Opioid analgesics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 61,
    code: '04070200',
    name: 'Drugs for neuropathic pain',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 62,
    code: '04070300',
    name: 'Antimigraine drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 63,
    code: '04070301',
    name: 'Drugs for acute migraine attack',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 64,
    code: '04070302',
    name: 'Drugs used in the prophylaxis of migraine',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 65,
    code: '04080000',
    name: 'Antiepileptics',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 66,
    code: '04080100',
    name: 'Drugs used in the control of epilepsy',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 67,
    code: '04080200',
    name: 'Drugs used in status epilepticus',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 68,
    code: '04090000',
    name: 'Drugs used in movement disorders',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 69,
    code: '04100000',
    name: 'Drugs used in substance dependence',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 70,
    code: '05000000',
    name: 'Infections',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 71,
    code: '05010000',
    name: 'Antibacterial drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 72,
    code: '05010100',
    name: 'Penicillins',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 73,
    code: '05010200',
    name: 'Cephalosporins, cephamycins, and other beta-lactams',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 74,
    code: '05010300',
    name: 'Tetracyclines',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 75,
    code: '05010400',
    name: 'Aminoglycosides',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 76,
    code: '05010500',
    name: 'Macrolides',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 77,
    code: '05010600',
    name: 'Quinolones',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 78,
    code: '05010700',
    name: 'Some other antibacterials',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 79,
    code: '05010800',
    name: 'Sulphonamides and trimethoprim',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 80,
    code: '05010900',
    name: 'Antituberculous drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 81,
    code: '05011000',
    name: 'Antileprotic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 82,
    code: '05020000',
    name: 'Antifungal drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 83,
    code: '05030000',
    name: 'Antiviral drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 84,
    code: '05030100',
    name: 'Non-antiretrovirals',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 85,
    code: '05030200',
    name: 'Antiretrovirals',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 86,
    code: '05040000',
    name: 'Antiprotozoal drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 87,
    code: '05040100',
    name: 'Antimalarials',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 88,
    code: '05040200',
    name: 'Other antiprotozoal drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 89,
    code: '05050000',
    name: 'Anthelmintics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 90,
    code: '05060000',
    name: 'Antiseptics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 91,
    code: '06000000',
    name: 'Endocrine system',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 92,
    code: '06010000',
    name: 'Drugs used in diabetes',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 93,
    code: '06010100',
    name: 'Insulins',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 94,
    code: '06010200',
    name: 'Oral antidiabetic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 95,
    code: '06020000',
    name: 'Thyroid and antithyroid drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 96,
    code: '06020100',
    name: 'Thyroid hormones',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 97,
    code: '06020200',
    name: 'Antithyroid drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 98,
    code: '06030000',
    name: 'Corticosteroids',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 99,
    code: '06040000',
    name: 'Sex hormones',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 100,
    code: '06040100',
    name: 'Female sex hormones',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 101,
    code: '06040200',
    name: 'Male sex hormones and antagonists',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 102,
    code: '06050000',
    name: 'Hypothalamic and pituitary hormones',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 103,
    code: '06050100',
    name: 'Hypothalamic and anterior pituitary hormones',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 104,
    code: '06050200',
    name: 'Posterior pituitary hormones and antagonists',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 105,
    code: '06060000',
    name: 'Drugs affecting bone metabolism',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 106,
    code: '06070000',
    name: 'Other endocrine drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 107,
    code: '06070100',
    name: 'Bromocriptine and other dopaminergic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 108,
    code: '06070200',
    name: 'Drugs affecting gonadotrophins',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 109,
    code: '07000000',
    name: 'Obstetrics, gynaecology and urinary-tract disorders',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 110,
    code: '07010000',
    name: 'Drugs used in obstetrics',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 111,
    code: '07010100',
    name: 'Prostaglandins, prostaglandins antagonists and oxytocics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 112,
    code: '07010200',
    name: 'Myometrial relaxants',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 113,
    code: '07020000',
    name: 'Treatment of vaginal and vulval conditions',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 114,
    code: '07030000',
    name: 'Contraceptives',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 115,
    code: '07040000',
    name: 'Drugs for genito-urinary disorders',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 116,
    code: '07040100',
    name: 'Drugs for benign prostatic hyperplasia',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 117,
    code: '07040200',
    name: 'Drugs for urinary frequency, enuresis, and incontinence',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 118,
    code: '07040300',
    name: 'Drugs used in alkalinisation of urine',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 119,
    code: '08000000',
    name: 'Malignant disease and immunosuppression',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 120,
    code: '08010000',
    name: 'Cytotoxic drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 121,
    code: '08010100',
    name: 'Alkylating drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 122,
    code: '08010200',
    name: 'Cytotoxic antibiotics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 123,
    code: '08010300',
    name: 'Antimetabolites',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 124,
    code: '08010400',
    name: 'Vinca alkaloids and etoposide',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 125,
    code: '08010500',
    name: 'Other antineoplastic drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 126,
    code: '08020000',
    name: 'Drugs affecting the immune response',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 127,
    code: '08030000',
    name: 'Sex hormones and hormone antagonists in malignant disease',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 128,
    code: '08030100',
    name: 'Progestogens, anti-estrogens and enzyme inhibitors',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 129,
    code: '08030200',
    name: 'Prostate cancer',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 130,
    code: '09000000',
    name: 'Nutrition and blood',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 131,
    code: '09010000',
    name: 'Whole blood, blood products and drugs used in some blood dis',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 132,
    code: '09010100',
    name: 'Whole blood and blood products',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 133,
    code: '09010200',
    name: 'Drugs used in hypoplastic, haemolytic and renal anaemias',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 134,
    code: '09010300',
    name: 'Drugs used in bone marrow transplantation',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 135,
    code: '09020000',
    name: 'Fluids and electrolytes',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 136,
    code: '09030000',
    name: 'Vitamins',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 137,
    code: '09040000',
    name: 'Intravenous nutrition',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 138,
    code: '09050000',
    name: 'Minerals',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 139,
    code: '09060000',
    name: 'Vitamins and minerals for precnancy and lactating mothers',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 140,
    code: '10000000',
    name: 'Musculoskeletal and joint diseases',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 141,
    code: '10010000',
    name: 'Drugs used in rheumatic diseases and gout',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 142,
    code: '10010100',
    name: 'Non-steroidal anti-inflammatory drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 143,
    code: '10010200',
    name: 'Disease-modifying antirheumatic drugs (DMARDs)',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 144,
    code: '10010300',
    name: 'Drugs for treatment of gout and hyperuricaemia',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 145,
    code: '10020000',
    name: 'Drugs used in neuromuscular disorders',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 146,
    code: '10020100',
    name: 'Drugs which enhance neuromuscular transmission',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 147,
    code: '10020200',
    name: 'Skeletal muscle relaxants',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 148,
    code: '10030000',
    name: 'Drugs for relief of soft-tissue inflammation',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 149,
    code: '10030100',
    name: 'Rubifacients',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 150,
    code: '11000000',
    name: 'Eye',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 151,
    code: '11010000',
    name: 'Anti-infective eye preparations',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 152,
    code: '11010100',
    name: 'Antibacterials and eye wash solution',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 153,
    code: '11010200',
    name: 'Antibacterials with corticosteroids',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 154,
    code: '11010300',
    name: 'Antifungals',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 155,
    code: '11010400',
    name: 'Antivirals',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 156,
    code: '11020000',
    name: 'Corticosteroids and other anti-inflammatory preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 157,
    code: '11030000',
    name: 'Mydriatics and cycloplegics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 158,
    code: '11040000',
    name: 'Drugs for treatment of glaucoma',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 159,
    code: '11050000',
    name: 'Local anaesthetics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 160,
    code: '11060000',
    name: 'Tear deficiency, ocular lubricants and astringents',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 161,
    code: '11070000',
    name: 'Ocular diagnostic and peri-operative preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 162,
    code: '12000000',
    name: 'Ear, nose, oropharynx  and oral cavity',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 163,
    code: '12010000',
    name: 'Drugs acting on the ear',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 164,
    code: '12020000',
    name: 'Drugs acting on the nose',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 165,
    code: '12020100',
    name: 'Drugs used in nasal allergy',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 166,
    code: '12020200',
    name: 'Topical nasal decongestants',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 167,
    code: '12030000',
    name: 'Drugs acting on the oropharynx and oral cavity',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 168,
    code: '12030100',
    name: 'Drugs used in treatment of oral ulcer',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 169,
    code: '12030200',
    name: 'Oropharyngeal antifungal drugs',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 170,
    code: '12030300',
    name: 'Antiseptics for root canal treatment',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 171,
    code: '12030400',
    name: 'Drugs used in prevention and treatment of dental plaque and',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 172,
    code: '12030500',
    name: 'Other  dental preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 173,
    code: '13000000',
    name: 'Skin',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 174,
    code: '13010000',
    name: 'Anti-infective skin preparations',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 175,
    code: '13010100',
    name: 'Antibacterial preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 176,
    code: '13010200',
    name: 'Antifungal preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 177,
    code: '13010300',
    name: 'Parasiticidal preparations',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 178,
    code: '13020000',
    name: 'Emollient and barrier preparations',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 179,
    code: '13030000',
    name: 'Topical antipruritics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 180,
    code: '13040000',
    name: 'Topical corticosteroids',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 181,
    code: '13050000',
    name: 'Other preparations for psoriasis (excluding topical corticos',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 182,
    code: '13060000',
    name: 'Preparations for warts and calluses',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 183,
    code: '14000000',
    name: 'Immunological products and vaccines',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 184,
    code: '15000000',
    name: 'Anaesthesia',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 185,
    code: '15010000',
    name: 'General anaesthesia',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 186,
    code: '15010100',
    name: 'Intravenous anaesthetics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 187,
    code: '15010200',
    name: 'Inhalational anaesthetics',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 188,
    code: '15010300',
    name: 'Muscle relaxants (Neuromuscular blocking drugs)',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 189,
    code: '15010400',
    name: 'Sedative and analgesic peri-operative drugs',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 190,
    code: '15010500',
    name: 'Anticholinesterases and antimuscarinic drugs used in anaesth',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 191,
    code: '15020000',
    name: 'Local anaesthesia',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 192,
    code: '16000000',
    name: 'Antidotes',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 193,
    code: '17000000',
    name: 'Contrast media and Radiopharmaceuticals',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 194,
    code: '17010000',
    name: 'X - ray contrast media, iodinated',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 195,
    code: '17010100',
    name: 'Drugs used in urography and computed tomography',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 196,
    code: '17010200',
    name: 'Drugs used in angiography',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 197,
    code: '17010300',
    name: 'Drugs used in myelography',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 198,
    code: '17010400',
    name: 'Drugs used in cardiovascular catheterization',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 199,
    code: '17010500',
    name: 'Drugs used in Intracavitary, Hysterosalpingography (HSG), Ur',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 200,
    code: '17020000',
    name: 'X - ray contrast media, non - iodinated',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 201,
    code: '17030000',
    name: 'Magnetic resonance imaging contrast media (MRI diagnostic ag',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 202,
    code: '17040000',
    name: 'Radiopharmaceuticals',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 203,
    code: '18000000',
    name: 'Miscellaneous',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 204,
    code: '19000000',
    name: 'สมุนไพร',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 205,
    code: '93000000',
    name: 'เวชภัณฑ์ที่มิใช่ยา',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 206,
    code: '94000000',
    name: 'วัสดุการแพทย์',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 207,
    code: '95000000',
    name: 'วัสดุวิทยาศาสตร์',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
  {
    id: 208,
    code: '96000000',
    name: 'เภสัชเคมีภัณฑ์',
    sub_commit_code: null,
    forecast: 10,
    is_hidden: false,
  },
  {
    id: 209,
    code: '97000000',
    name: 'อื่นๆ',
    sub_commit_code: null,
    forecast: null,
    is_hidden: false,
  },
];

// ============================================================================
// Seed Function
// ============================================================================

export async function seed(knex: Knex): Promise<void> {
  console.log(
    '\n═══════════════════════════════════════════════════════════════',
  );
  console.log('  🌱 SEEDING ED GROUPS (Essential Drugs Therapeutic Groups)');
  console.log(
    '═══════════════════════════════════════════════════════════════\n',
  );

  // Ensure we're in inventory schema
  await knex.raw(`SET search_path TO inventory, public`);

  // Seed ED Groups
  console.log('📋 Seeding ed_groups...');
  let inserted = 0;
  let updated = 0;

  for (const item of ED_GROUPS) {
    const result = await knex.raw(
      `
      INSERT INTO inventory.ed_groups (id, code, name, sub_commit_code, forecast, is_hidden, is_active, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, true, NOW(), NOW())
      ON CONFLICT (code) DO UPDATE SET
        name = EXCLUDED.name,
        sub_commit_code = EXCLUDED.sub_commit_code,
        forecast = EXCLUDED.forecast,
        is_hidden = EXCLUDED.is_hidden,
        updated_at = NOW()
      RETURNING (xmax = 0) AS inserted
    `,
      [
        item.id,
        item.code,
        item.name,
        item.sub_commit_code,
        item.forecast,
        item.is_hidden,
      ],
    );

    if (result.rows[0]?.inserted) {
      inserted++;
    } else {
      updated++;
    }
  }

  // Reset sequence to max id + 1
  await knex.raw(`
    SELECT setval('inventory.ed_groups_id_seq',
      COALESCE((SELECT MAX(id) FROM inventory.ed_groups), 0) + 1,
      false
    )
  `);

  console.log(`   ✅ ${inserted} ed_groups inserted, ${updated} updated`);

  console.log(
    '\n═══════════════════════════════════════════════════════════════',
  );
  console.log('  ✅ ED GROUPS SEEDING COMPLETE');
  console.log(
    '═══════════════════════════════════════════════════════════════\n',
  );

  // Summary
  const count = await knex.raw(
    `SELECT COUNT(*) as total FROM inventory.ed_groups`,
  );
  console.log(`📊 Total ED Groups: ${count.rows[0].total} records`);
  console.log('');
}
